title: "API reference"
email: documentation@epages.com
app_scopes: ["customers_read", "customers_write", "legal_read", "legal_write", "newsletters_read", "orders_read", "orders_write", "products_read", "products_write", "products_read_batch", "scripttags_read", "scripttags_write"]
url: "https://developer.epages.com"
baseurl: ""
github_url: "https://github.com/ePages-de/epages-docs"
future: true
raml:
- key_prefix: "apps-api-"
  url_prefix: "apps/api-reference/"
  root_file: "_raml/apps/api.raml"
  api_versions: "_raml/**/*/api.raml"
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
  - _pages
exclude:
- build.sh
- Capfile
- CONTRIBUTING.md
- Dockerfile
- Jenkinsfile
- docker-compose.yml
- Gemfile
- Gemfile.lock
- LICENSE-CC-BY-40.txt
- LICENSE-MIT.txt
- Rakefile
- README.md
- config/
- vendor
- firebase.json
gem:
- jekyll-include-cache
plugins:
- bourbon
- neat
- rouge
